final touch on main-branch pipieline

diff --git a/.github/workflows/main-branch-pipeline.yml b/.github/workflows/main-branch-pipeline.yml
--- a/.github/workflows/main-branch-pipeline.yml
+++ b/.github/workflows/main-branch-pipeline.yml
@@ -54,6 +54,8 @@ jobs:
   setup:
     name: Setup | Neon workflow
     runs-on: ubuntu-latest
+    needs: validate-env
+    if: success()
     outputs:
       branch: ${{ steps.branch_name.outputs.current_branch }}
     steps:
@@ -64,8 +66,10 @@ jobs:
   deploy_to_neon:
     name: Deploy to Neon Using Deployment Branch
     needs: setup
+    if: success()
     runs-on: ubuntu-latest
     steps:
+      # STEP-1: Create a new Branch for deployment
       - name: Use Neon Deployment Branch
         id: use_neon_branch
         uses: neondatabase/create-branch-action@v5
@@ -74,18 +78,38 @@ jobs:
           username: "Tasks_owner"
           parent: main
           database: Tasks
-          branch_name: Task-deployment
+          branch_name: Task-deployment  # <-------------------- Add the branch name to be created
           api_key: ${{ secrets.NEON_API_KEY }}
 
-      - name: Run Deployment Tasks
-        run: npm run db:migrate
+      # STEP-2: Run Migration
+      - name: Check Database Connection and Run Migration
+        run: |
+          # Check if DATABASE_URL is set
+          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
+            echo "DATABASE_URL is not set. Cannot proceed with migration."
+            exit 1
+          fi
+
+          # Test if the database is reachable
+          PGPASSWORD=$(echo "${{ secrets.DATABASE_URL }}" | sed -n 's/.*:\/\/*:\([^@]*\).*/\1/p') \
+          psql $(echo "${{ secrets.DATABASE_URL }}" | sed -n 's/\(.*@\)\(.*\)\/.*/\2/p') -c '\q'
+
+          if [ $? -ne 0 ]; then
+            echo "Cannot connect to the database. Please check the connection settings."
+            exit 1
+          fi
+
+          # Run the migration if everything is okay
+          yarn run db:migrate
         env:
           DATABASE_URL: "${{ secrets.DATABASE_URL }}"
 
 
+  # STEP-3: if no error on Migration Ok then Deploy to vercel
   deploy_to_vercel:
     name: Deploy to Vercel
     needs: deploy_to_neon
+    if : success()
     runs-on: ubuntu-latest
     steps:
       - name: Deploy to Vercel
@@ -97,9 +121,11 @@ jobs:
           working-directory: ./ # Update as necessary
 
   build:
+    # STEP-4: if Deploy to Vercel Ok, then Deploy the docs
     name: Build Documentation
     runs-on: ubuntu-latest
     needs: deploy_to_vercel
+    if: success()
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -117,14 +143,16 @@ jobs:
           publish_dir: ./docs
 
   delete_neon_branch:
+    # STEP-5: Wait for the end of the process and clean up regardless of success or failure
     name: Delete Neon Deployment Branch
     runs-on: ubuntu-latest
-    needs: [deploy_to_neon, deploy_to_vercel, build] # Depends on previous jobs
+    needs: [ deploy_to_neon, deploy_to_vercel, build ] # Depends on previous jobs
     if: always() # Run regardless of success or failure
     steps:
       - name: Delete Neon Deployment Branch
-        run: |
-          neonctl branch delete deployment --project-id ${{ secrets.NEON_PROJECT_ID }}
-        env:
-          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
-          NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
+        uses: neondatabase/delete-branch-action@v3
+        with:
+          api_key: ${{ secrets.NEON_API_KEY }}
+          project_id: ${{ secrets.NEON_PROJECT_ID }}
+          branch_name: Task-deployment # <-------------------- Add the branch name to be deleted
+
